In [1]:
import pandas as pd
import numpy as np
import datetime
import math
import os
import matplotlib.pyplot as plt
from pylab import rcParams

plt.style.use('ggplot')
%pylab inline --no-import-all


#インプットデータ
year="2019"
month="04"
day="15"
time="000000"
file_dir_path="Realtime_CSV/"
#開始日本時間（UTC+9）
#緯度経度：　北緯33度35.0分　東経130度27.1分

start_TimeJP ='2019-05-06 01:00'
finish_TimeJP ='2019-05-11 00:00'


#################
#EveryTime check!
#################

input_data = pd.read_csv('Hakata_realtime_2019_05_13.csv') #データ2

#風力発電初期値
Pr=2.3 #定格電力
V_CIN=2.5 #カットイン風速
V_rat=20 #
V_CO=20 #カットアウト風速
H=30.5 #高さ
H_top=80 #風速計測の高さ（高い）
H_ref=10 #風速計測の高さ（低い）
atm_pre0=1.225 #基準大気圧
total_cost = 1575000 #コスト[yen/unit]
Op_year = 10 #稼動年数
cost = (total_cost/(Op_year*365*24)) #コスト[yen/hour/unit]

Populating the interactive namespace from numpy and matplotlib

In [2]:
pwd()

'/home/yuichiro/Miniconda/Weather/GribToCSV'

# Set or Modify parameters below!!

In [3]:
input_data[:5]

,Year,Month,Day,Hour,Minute,Temperature [2 m above gnd],Mean Sea Level Pressure [MSL],Radiation [W],Wind Speed [10 m above gnd]
0,2019,5,6,1,0,18.2,1,0.0,1.0
1,2019,5,6,2,0,18.3,1,0.0,1.5
2,2019,5,6,3,0,18.1,1,0.0,2.7
3,2019,5,6,4,0,18.1,1,0.0,2.1
4,2019,5,6,5,0,18.1,1,0.0,1.9

# Solar calc

In [4]:
#太陽光発電初期値

#インプットデータ
#input_rad = pd.read_csv('rad.csv')#encordingはUTF-8なので注意 unitは、MJ/m2
input_csv_parameter = pd.read_csv('PV_input_parameter.csv')

In [5]:
#1列目以外を抽出
input_csv_parameter = input_csv_parameter.iloc[:, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18]]

Gsc = float(input_csv_parameter.iat[0,0])#float(1.367)#the solar constant [1.367 kW/m2]
Gt_NOCT = float(input_csv_parameter.iat[0,1]) #the solar radiation at which the NOCT is defined [0.8 kW/m2]
Ta_NOCT = float(input_csv_parameter.iat[0,2])+273.15 #the ambient temperature at which the NOCT is defined [20°C]
Tc_NOCT = float(input_csv_parameter.iat[0,3])+273.15 #the nominal operating cell temperature [°C]
Tc_STC = float(input_csv_parameter.iat[0,4])+273.15 #the PV cell temperature under standard test conditions [25°C]

YPV = float(input_csv_parameter.iat[0,6]) #the rated capacity of the PV array, meaning its power output under standard test conditions [kW]
ap = float(input_csv_parameter.iat[0,7]) #Module Efficiency(Pmax)[%/℃]
beta= float(input_csv_parameter.iat[0,8])  #the slope of the surface [°]
eta_c = float(input_csv_parameter.iat[0,9]) #the solar absorptance and the solar transmittance[%]
fpv = float(input_csv_parameter.iat[0,10]) #the PV derating factor [%]
ganma = float(input_csv_parameter.iat[0,11]) #the azimuth of the surface [°]
lam=float(input_csv_parameter.iat[0,12])#the longitude [°]
phi=float(input_csv_parameter.iat[0,13])#the latitude [°]
rho_g = float(input_csv_parameter.iat[0,14]) # the ground reflectance, which is also called the albedo [%]
tau_a = float(input_csv_parameter.iat[0,15]) #the solar absorptance and the solar transmittance[%]
_Gt_STC =float(1) #the incident radiation at standard test conditions [1 kW/m2]
UL = (tau_a*Gt_NOCT)/(Tc_NOCT-Ta_NOCT)
#UL = float(input_csv_parameter.iat[0,5])
total_cost = float(input_csv_parameter.iat[0,16]) #total cost
Op_year = float(input_csv_parameter.iat[0,17]) #oparation year
cost = total_cost/(Op_year*365*24)#cost[yen/kW/h]

In [6]:
input_csv_parameter

,Gsc,Gt_NOCT,Ta_NOCT,Tc_NOCT,Tc_STC,UL,YPV,ap,beta,eta_c,fpv,ganma,lam,phi,rho_g,tau_a,total_cost,Op_year
0,1.367,0.8,20,44,25,3,194.44,-0.00258,33,0.194,0.8,0,130.25,33.349,0.2,0.9,199165,15

In [7]:
#入力初期値をデータフレームにする。
input_parameter_name=['Gsc','Gt_NOCT','Ta_NOCT','Tc_NOCT','Tc_STC','UL',\
                      'YPV','ap','beta','eta_c','fpv','ganma','lam','phi',\
                      'rho_g','tau_a','total_cost','Op_year','cost']

input_parameter_list=[Gsc,Gt_NOCT,Ta_NOCT,Tc_NOCT,Tc_STC,UL,\
                      YPV,ap,beta,eta_c,fpv,ganma,lam,phi,\
                      rho_g,tau_a,total_cost,Op_year,cost]

def float2DataFrame(name,list):
    df0=pd.DataFrame({str(name[0]): [list[0]]})
    for i in range(len(list)-1):
        a = float(list[i+1])
        df=pd.DataFrame({str(name[i+1]): [a]})
        df0 =pd.concat([df0, df], axis=1)
    return df0

input_parameter=float2DataFrame(input_parameter_name,input_parameter_list)
input_parameter

,Gsc,Gt_NOCT,Ta_NOCT,Tc_NOCT,Tc_STC,UL,YPV,ap,beta,eta_c,fpv,ganma,lam,phi,rho_g,tau_a,total_cost,Op_year,cost
0,1.367,0.8,293.15,317.15,298.15,0.03,194.44,-0.00258,33.0,0.194,0.8,0.0,130.25,33.349,0.2,0.9,199165.0,15.0,1.515715

# Visualizing

# RealTime validation

In [8]:
#列名の変更
input_data.columns = ['Year', 'Month', 'Day','Hour', 'Minute','Real_Temperature(2m)[°C]', 'Real_Mean Sea Level Pressure[hpa]', \
                          'Real_Radiation[W/m2]','Real_Wind Speed(10m)[m/s]']


#日付型などの変更
input_data['Time'] = input_data[['Year', 'Month', 'Day','Hour']].apply(lambda x: '{}@{}@{}@{}'.format(x[0], x[1], x[2],x[3]), axis=1)
Time = input_data['Time']
input_data['Time'] =pd.to_datetime(Time, format='%Y@%m@%d@%H')

In [9]:
Realtime=pd.concat([input_data],axis=1,sort=False)

In [10]:
#ωの計算
Realtime['ts'] = Realtime['Hour']
Realtime['ω'] = (Realtime['ts'].values - 12 )*15#degree
Realtime['n'] = Realtime['Time'] .dt.dayofyear
Realtime[:5]

,Year,Month,Day,Hour,Minute,Real_Temperature(2m)[°C],Real_Mean Sea Level Pressure[hpa],Real_Radiation[W/m2],Real_Wind Speed(10m)[m/s],Time,ts,ω,n
0,2019,5,6,1,0,18.2,1,0.0,1.0,2019-05-06 01:00:00,1,-165,126
1,2019,5,6,2,0,18.3,1,0.0,1.5,2019-05-06 02:00:00,2,-150,126
2,2019,5,6,3,0,18.1,1,0.0,2.7,2019-05-06 03:00:00,3,-135,126
3,2019,5,6,4,0,18.1,1,0.0,2.1,2019-05-06 04:00:00,4,-120,126
4,2019,5,6,5,0,18.1,1,0.0,1.9,2019-05-06 05:00:00,5,-105,126

In [11]:
Realtime['δ the solar declination']=23.45*np.sin(np.deg2rad(360*(284+Realtime['n'].values)/365))#degree

delta=Realtime['δ the solar declination'].values#degree

In [12]:
#角度をdeg2rad
omega = np.deg2rad(Realtime['ω'].values)#rad
delta =np.deg2rad(delta)#rad
phi =math.radians(phi)#rad
beta =math.radians(beta)#rad
ganma =math.radians(ganma)#rad
lam =math.radians(lam)#rad

#cosθの計算
Realtime['cosθ'] = np.sin(delta)*math.sin(phi)*math.cos(beta)\
                    -np.sin(delta)*math.cos(phi)*math.sin(beta)*math.cos(ganma)\
                    +np.cos(delta)*math.cos(phi)*math.cos(beta)*np.cos(omega)\
                    +np.cos(delta)*math.sin(phi)*math.sin(beta)*math.cos(ganma)*np.cos(omega)\
                    +np.cos(delta)*math.sin(beta)*math.sin(ganma)*np.sin(omega)
                    
cos_theta = Realtime['cosθ'].values

In [13]:
#θの計算
Realtime['θ(radian)'] = np.arccos(Realtime['cosθ'].values)#rad

Realtime['θ(degree)'] = np.rad2deg(Realtime['θ(radian)'].values)#degree

Theta_deg = Realtime['θ(radian)'].values#rad

#cosθzの計算
Realtime['cosθz'] =math.cos(phi)*np.cos(delta)*np.cos(omega)\
                        +math.sin(phi)*np.sin(delta)

cos_theta_z = Realtime['cosθz'].values

Realtime['θz(radian)'] = np.arccos(Realtime['cosθz'].values)#rad

Realtime['θz(degree)'] = np.rad2deg(Realtime['θz(radian)'].values)#degree

Theta_z_deg = Realtime['θz(radian)'].values#rad

#theta degree ndarray
theta = Realtime['θ(radian)'].values#rad

#theta degree ndarray
theta_z = Realtime['θz(radian)'].values#rad

#decimals=1で小数点第2位を四捨五入する
cos_theta = np.round(cos_theta, decimals=1)
cos_theta_z = np.round(cos_theta_z, decimals=1)
Theta_deg =np.round(Theta_deg, decimals=0)
Theta_deg_z = np.round(Theta_z_deg, decimals=0)

cos_theta = np.cos(Theta_deg)
cos_theta_z = np.cos(Theta_z_deg)
Realtime

,Year,Month,Day,Hour,Minute,Real_Temperature(2m)[°C],Real_Mean Sea Level Pressure[hpa],Real_Radiation[W/m2],Real_Wind Speed(10m)[m/s],Time,ts,ω,n,δ the solar declination,cosθ,θ(radian),θ(degree),cosθz,θz(radian),θz(degree)
0,2019,5,6,1,0,18.2,1,0.000000,1.0,2019-05-06 01:00:00,1,-165,126,16.402298,-0.924878,2.751511,157.649965,-0.618802,2.238013,128.228677
1,2019,5,6,2,0,18.3,1,0.000000,1.5,2019-05-06 02:00:00,2,-150,126,16.402298,-0.829045,2.548194,146.000764,-0.538747,2.139746,122.598402
2,2019,5,6,3,0,18.1,1,0.000000,2.7,2019-05-06 03:00:00,3,-135,126,16.402298,-0.676597,2.313927,132.578274,-0.411399,1.994785,114.292761
3,2019,5,6,4,0,18.1,1,0.000000,2.1,2019-05-06 04:00:00,4,-120,126,16.402298,-0.477922,2.069084,118.549799,-0.245436,1.818766,104.207598
4,2019,5,6,5,0,18.1,1,0.000000,1.9,2019-05-06 05:00:00,5,-105,126,16.402298,-0.246561,1.819927,104.274113,-0.052168,1.622988,92.990343
5,2019,5,6,6,0,18.1,1,5.555556,1.2,2019-05-06 06:00:00,6,-90,126,16.402298,0.001720,1.569076,89.901450,0.155235,1.414931,81.069585
6,2019,5,6,7,0,18.4,1,66.666667,1.5,2019-05-06 07:00:00,7,-75,126,16.402298,0.250001,1.318115,75.522416,0.362637,1.199700,68.737753
7,2019,5,6,8,0,20.1,1,263.888889,0.9,2019-05-06 08:00:00,8,-60,126,16.402298,0.481362,1.068588,61.225576,0.555906,0.981344,56.226890
8,2019,5,6,9,0,20.4,1,119.444444,1.9,2019-05-06 09:00:00,9,-45,126,16.402298,0.680037,0.822983,47.153477,0.721869,0.764297,43.791010
9,2019,5,6,10,0,20.0,1,72.222222,0.9,2019-05-06 10:00:00,10,-30,126,16.402298,0.832485,0.587218,33.645132,0.849217,0.556296,31.873402
10,2019,5,6,11,0,20.8,1,247.222222,1.3,2019-05-06 11:00:00,11,-15,126,16.402298,0.928318,0.380933,21.825872,0.929271,0.378361,21.678498
11,2019,5,6,12,0,22.9,1,666.666667,1.9,2019-05-06 12:00:00,12,0,126,16.402298,0.961005,0.280183,16.053298,0.956576,0.295776,16.946702
12,2019,5,6,13,0,23.0,1,480.555556,4.1,2019-05-06 13:00:00,13,15,126,16.402298,0.928318,0.380933,21.825872,0.929271,0.378361,21.678498
13,2019,5,6,14,0,21.8,1,597.222222,5.5,2019-05-06 14:00:00,14,30,126,16.402298,0.832485,0.587218,33.645132,0.849217,0.556296,31.873402
14,2019,5,6,15,0,21.6,1,638.888889,6.8,2019-05-06 15:00:00,15,45,126,16.402298,0.680037,0.822983,47.153477,0.721869,0.764297,43.791010
15,2019,5,6,16,0,21.0,1,475.000000,5.3,2019-05-06 16:00:00,16,60,126,16.402298,0.481362,1.068588,61.225576,0.555906,0.981344,56.226890
16,2019,5,6,17,0,19.8,1,422.222222,6.3,2019-05-06 17:00:00,17,75,126,16.402298,0.250001,1.318115,75.522416,0.362637,1.199700,68.737753
17,2019,5,6,18,0,18.3,1,213.888889,7.6,2019-05-06 18:00:00,18,90,126,16.402298,0.001720,1.569076,89.901450,0.155235,1.414931,81.069585
18,2019,5,6,19,0,16.9,1,50.000000,6.5,2019-05-06 19:00:00,19,105,126,16.402298,-0.246561,1.819927,104.274113,-0.052168,1.622988,92.990343
19,2019,5,6,20,0,16.3,1,0.000000,5.7,2019-05-06 20:00:00,20,120,126,16.402298,-0.477922,2.069084,118.549799,-0.245436,1.818766,104.207598
20,2019,5,6,21,0,16.1,1,0.000000,4.2,2019-05-06 21:00:00,21,135,126,16.402298,-0.676597,2.313927,132.578274,-0.411399,1.994785,114.292761
21,2019,5,6,22,0,15.7,1,0.000000,4.4,2019-05-06 22:00:00,22,150,126,16.402298,-0.829045,2.548194,146.000764,-0.538747,2.139746,122.598402
22,2019,5,6,23,0,15.1,1,0.000000,6.6,2019-05-06 23:00:00,23,165,126,16.402298,-0.924878,2.751511,157.649965,-0.618802,2.238013,128.228677
23,2019,5,7,0,0,14.8,1,0.000000,5.5,2019-05-07 00:00:00,0,-180,127,16.688348,-0.956114,2.844235,162.962652,-0.642288,2.268276,129.962652
24,2019,5,7,1,0,14.4,1,0.000000,6.3,2019-05-07 01:00:00,1,-165,127,16.688348,-0.923476,2.747839,157.439596,-0.615024,2.233212,127.953632
25,2019,5,7,2,0,14.1,1,0.000000,2.4,2019-05-07 02:00:00,2,-150,127,16.688348,-0.827785,2.545944,145.871835,-0.535088,2.135408,122.349869
26,2019,5,7,3,0,13.8,1,0.000000,2.4,2019-05-07 03:00:00,3,-135,127,16.688348,-0.675562,2.312523,132.497835,-0.407928,1.990980,114.074772
27,2019,5,7,4,0,13.4,1,0.000000,2.5,2019-05-07 04:00:00,4,-120,127,16.688348,-0.477182,2.068242,118.501541,-0.242211,1.815441,104.017084
28,2019,5,7,5,0,13.2,1,0.000000,1.2,2019-05-07 05:00:00,5,-105,127,16.688348,-0.246164,1.819517,104.250636,-0.049229,1.620046,92.821773
29,2019,5,7,6,0,13.7,1,13.888889,2.4,2019-05-07 06:00:00,6,-90,127,16.688348,0.001749,1.569047,89.899780,0.157866,1.412267,80.916962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138,2019,5,11,19,0,20.4,1,47.222222,3.0,2019-05-11 19:00:00,19,105,131,17.782271,-0.244589,1.817892,104.157539,-0.037982,1.608787,92.176723
139,2019,5,11,20,0,20.5,1,0.000000,1.6,2019-05-11 20:00:00,20,120,131,17.782271,-0.474243,2.064900,118.310066,-0.229824,1.802693,103.286711
140,2019,5,11,21,0,20.2,1,0.000000,1.2,2019-05-11 21:00:00,21,135,131,17.782271,-0.671451,2.306962,132.179173,-0.394563,1.976388,113.238699
141,2019,5,11,22,0,19.8,1,0.000000,1.7,2019-05-11 22:00:00,22,150,131,17.782271,-0.822775,2.537072,145.363512,-0.520971,2.118784,121.397408
142,2019,5,11,23,0,19.6,1,0.000000,0.8,2019-05-11 23:00:00,23,165,131,17.782271,-0.917900,2.733553,156.621037,-0.600435,2.214841,126.901033
143,2019,5,12,0,0,19.1,1,0.000000,0.8,2019-05-12 00:00:00,0,-180,132,18.042778,-0.948921,2.820596,161.608222,-0.623992,2.244637,128.608222
144,2019,5,12,1,0,18.5,1,0.000000,0.4,2019-05-12 01:00:00,1,-165,132,18.042778,-0.916523,2.730096,156.422991,-0.596928,2.210463,126.650196
145,2019,5,12,2,0,18.5,1,0.000000,1.1,2019-05-12 02:00:00,2,-150,132,18.042778,-0.821537,2.534898,145.238970,-0.517581,2.114818,121.170132
146,2019,5,12,3,0,18.9,1,0.000000,1.4,2019-05-12 03:00:00,3,-135,132,18.042778,-0.670436,2.305593,132.100733,-0.391358,1.972903,113.039043
147,2019,5,12,4,0,18.8,1,0.000000,1.7,2019-05-12 04:00:00,4,-120,132,18.042778,-0.473517,2.064076,118.262859,-0.226862,1.799650,103.112372
148,2019,5,12,5,0,18.4,1,0.000000,0.4,2019-05-12 05:00:00,5,-105,132,18.042778,-0.244201,1.817492,104.134596,-0.035301,1.606105,92.023029
149,2019,5,12,6,0,18.1,1,11.111111,0.9,2019-05-12 06:00:00,6,-90,132,18.042778,0.001887,1.568910,89.891906,0.170269,1.399694,80.196569
150,2019,5,12,7,0,19.1,1,122.222222,0.5,2019-05-12 07:00:00,7,-75,132,18.042778,0.247974,1.320208,75.642356,0.375838,1.185495,67.923873
151,2019,5,12,8,0,20.3,1,241.666667,0.2,2019-05-12 08:00:00,8,-60,132,18.042778,0.477291,1.073228,61.491408,0.567399,0.967453,55.430977
152,2019,5,12,9,0,21.1,1,430.555556,2.6,2019-05-12 09:00:00,9,-45,132,18.042778,0.674209,0.830903,47.607221,0.731895,0.749697,42.954479
153,2019,5,12,10,0,23.2,1,644.444444,2.3,2019-05-12 10:00:00,10,-30,132,18.042778,0.825310,0.600045,34.380027,0.858118,0.539203,30.894069
154,2019,5,12,11,0,24.7,1,763.888889,2.9,2019-05-12 11:00:00,11,-15,132,18.042778,0.920297,0.401959,23.030533,0.937465,0.355522,20.369898
155,2019,5,12,12,0,25.1,1,936.111111,4.0,2019-05-12 12:00:00,12,0,132,18.042778,0.952694,0.308815,17.693778,0.964529,0.267144,15.306222
156,2019,5,12,13,0,24.2,1,958.333333,4.9,2019-05-12 13:00:00,13,15,132,18.042778,0.920297,0.401959,23.030533,0.937465,0.355522,20.369898
157,2019,5,12,14,0,22.1,1,777.777778,5.7,2019-05-12 14:00:00,14,30,132,18.042778,0.825310,0.600045,34.380027,0.858118,0.539203,30.894069
158,2019,5,12,15,0,21.5,1,263.888889,3.9,2019-05-12 15:00:00,15,45,132,18.042778,0.674209,0.830903,47.607221,0.731895,0.749697,42.954479
159,2019,5,12,16,0,20.9,1,238.888889,4.5,2019-05-12 16:00:00,16,60,132,18.042778,0.477291,1.073228,61.491408,0.567399,0.967453,55.430977
160,2019,5,12,17,0,20.2,1,133.333333,3.8,2019-05-12 17:00:00,17,75,132,18.042778,0.247974,1.320208,75.642356,0.375838,1.185495,67.923873
161,2019,5,12,18,0,20.2,1,63.888889,2.5,2019-05-12 18:00:00,18,90,132,18.042778,0.001887,1.568910,89.891906,0.170269,1.399694,80.196569
162,2019,5,12,19,0,19.7,1,19.444444,1.8,2019-05-12 19:00:00,19,105,132,18.042778,-0.244201,1.817492,104.134596,-0.035301,1.606105,92.023029
163,2019,5,12,20,0,19.3,1,0.000000,2.7,2019-05-12 20:00:00,20,120,132,18.042778,-0.473517,2.064076,118.262859,-0.226862,1.799650,103.112372
164,2019,5,12,21,0,18.9,1,0.000000,2.4,2019-05-12 21:00:00,21,135,132,18.042778,-0.670436,2.305593,132.100733,-0.391358,1.972903,113.039043
165,2019,5,12,22,0,18.7,1,0.000000,1.1,2019-05-12 22:00:00,22,150,132,18.042778,-0.821537,2.534898,145.238970,-0.517581,2.114818,121.170132
166,2019,5,12,23,0,18.7,1,0.000000,1.8,2019-05-12 23:00:00,23,165,132,18.042778,-0.916523,2.730096,156.422991,-0.596928,2.210463,126.650196
167,2019,5,13,0,0,18.3,1,0.000000,1.1,2019-05-13 00:00:00,0,-180,133,18.297938,-0.947507,2.816142,161.353062,-0.620506,2.240184,128.353062

In [14]:
#Gon(the extraterrestrial normal radiation)[kW/m2]の計算
Realtime['Gon(the extraterrestrial normal radiation)[kW/m2]'] \
=Gsc*(1+0.033*np.cos(np.deg2rad(360*Realtime['n'].values/365)))#np.deg2rad

Gon =Realtime['Gon(the extraterrestrial normal radiation)[kW/m2]'].values

#Go(the extraterrestrial horizontal radiation [kW/m2])の計算
Realtime['Go(the extraterrestrial horizontal radiation)[kW/m2]'] \
=Gon*np.abs(cos_theta_z)

Go = Realtime['Go(the extraterrestrial horizontal radiation)[kW/m2]'] .values

In [15]:
#_Go(the extraterrestrial horizontal radiation averaged over the time step )[kW/m2]の計算

def step_minus(x):  #再帰関数　引数[2]-引数[1] ndarrayで返す ndarrayを引数
    x = list(x)
    y = [0]
    y.extend(x) #引数2
    x.extend([0]) #引数1
    y = np.array(y)
    x = np.array(x)
    ans = y - x
    return ans[1:]#[1:]or [:8760]


Realtime['_Go(the extraterrestrial horizontal radiation averaged over the time step )[kW/m2]'] \
=(12/np.pi)*Gon*np.abs(np.cos(phi)*np.cos(delta)*step_minus(np.sin(omega))\
+((np.pi/180)*step_minus(omega)*np.sin(phi)*np.sin(delta)))

_Go = Realtime['_Go(the extraterrestrial horizontal radiation averaged over the time step )[kW/m2]']

In [16]:
Realtime['the global horizontal radiation[kW/m2]']=\
Realtime['Real_Radiation[W/m2]'].values/1000

_G = Realtime['the global horizontal radiation[kW/m2]'].values
Realtime['the global horizontal radiation[kW/m2]'] = _G

In [17]:
#ktの計算
Realtime['kt(the clearness index)'] =_G/_Go #_G2
kt = np.abs(Realtime['kt(the clearness index)'].values)

_Go=kt/_G

#_Gdの計算
#２の３乗#累乗np.power(2, 3)
def if_kt(x):
    x = np.abs(x)
    ans = np.where(x>=0.8,0.165,np.where(x < 0.22, 1-0.09*x,0.95511-0.1604*x+4.388*x*x-16.638*x*x*x+12.336*x*x*x*x))
    return ans

Realtime['_Gd(the diffuse radiation)[kW/m2]']=_G*if_kt(kt)
_Gd = Realtime['_Gd(the diffuse radiation)[kW/m2]'].values

#_Gb(the beam radiation)の計算
Realtime['_Gb(the beam radiation)[kW/m2]']=_G-_Gd

_Gb = Realtime['_Gb(the beam radiation)[kW/m2]'].values

#_G
Realtime['_G']=_Gd+_Gb

/home/yuichiro/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """

In [18]:
#Rbの計算
#input_data['Rb']= cos_theta/cos_theta_z
Realtime['Rb']= np.abs(Realtime['cosθ'].values/Realtime['cosθz'].values)

#thetaの計算がjupyterだとうまくいかない泣
#input_data['Rb']=Rb
Rb = Realtime['Rb'].values

#発散の処理 要考察 yを超えるとzになる　
def div(x,y,z):
    x = abs(x)
    ans = np.where(x>y,z,x)
    return ans
#Rb = div(Rb,3,3)
#input_data['Rb']= div(Rb,3,3)
Realtime['Rb']= Rb

#Afの計算
Realtime['Af']=_Gb/_Go #_G2

Af = Realtime['Af'].values

#fの計算
Realtime['f']=np.sqrt(_Gb/_G) #_G2
    #欠損値を0で置き換える
Realtime=Realtime.fillna(0)
f = Realtime['f'].values

/home/yuichiro/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:24: RuntimeWarning: invalid value encountered in true_divide

In [19]:
def sin3(x):
    return math.sin(x)*math.sin(x)*math.sin(x)

#_Gtの計算#２の３乗#累乗np.power(2, 3) np.power(np.sin(beta/2),3) or def 3sin(x)
_Gt=(_Gb+_Gd*Af)*Rb\
                +(_Gd*(1-Af)*((1+math.cos(beta))/2)\
                *np.abs(1+f*sin3(beta/2)))\
                +(_G*rho_g*((1-math.cos(beta))/2))
_Gt[np.isnan(_Gt)] = 0
        
Realtime['_Gt']  = _Gt

In [20]:
#Tc(the PV cell temperature [°C])の計算
Realtime['temperature[K]']=Realtime['Real_Temperature(2m)[°C]']+ 273.15
Ta = Realtime['temperature[K]'].values


#input_data['Tc(the PV cell temperature)[°C]']\
#= Ta+_Gt*(tau_a/UL)*(1-eta_c/tau_a)

Realtime['Tc(the PV cell temperature)[K]']\
= Ta+_Gt*((Tc_NOCT-Ta_NOCT)/Gt_NOCT)*(1-eta_c/tau_a)

Tc = Realtime['Tc(the PV cell temperature)[K]'].values

Realtime['Real_Tc(the PV cell temperature)[°C]']=Realtime['Tc(the PV cell temperature)[K]']-273.15

#Ppv(the output of the PV array)[kW]の計算   #発散の処理div(x)を使用
#input_data['Ppv(the output of the PV array)[Wh]']\
#=div(YPV*fpv*(_Gt/_Gt_STC)*np.abs((1+ap*(Tc-Tc_STC))), YPV,YPV)

#Ppv(the output of the PV array)[kW]の計算   #発散の処理div(x)を使用2
Realtime['Real_Ppv(the output of the PV array)[Wh]']\
=YPV*fpv*(_Gt/_Gt_STC)*np.abs((1+ap*(Tc-Tc_STC)))

Ppv = Realtime['Real_Ppv(the output of the PV array)[Wh]'].values

#input_data['Left'] = YPV*fpv*(_Gt/_Gt_STC)
#input_data['Right'] =np.abs((1+ap*(Tc-Tc_STC)))

Realtime[:10]

,Year,Month,Day,Hour,Minute,Real_Temperature(2m)[°C],Real_Mean Sea Level Pressure[hpa],Real_Radiation[W/m2],Real_Wind Speed(10m)[m/s],Time,...,_Gb(the beam radiation)[kW/m2],_G,Rb,Af,f,_Gt,temperature[K],Tc(the PV cell temperature)[K],Real_Tc(the PV cell temperature)[°C],Real_Ppv(the output of the PV array)[Wh]
0,2019,5,6,1,0,18.2,1,0.000000,1.0,2019-05-06 01:00:00,...,0.000000,0.000000,1.494628,0.000000,0.000000,0.000000,291.35,291.350000,18.200000,0.000000
1,2019,5,6,2,0,18.3,1,0.000000,1.5,2019-05-06 02:00:00,...,0.000000,0.000000,1.538838,0.000000,0.000000,0.000000,291.45,291.450000,18.300000,0.000000
2,2019,5,6,3,0,18.1,1,0.000000,2.7,2019-05-06 03:00:00,...,0.000000,0.000000,1.644624,0.000000,0.000000,0.000000,291.25,291.250000,18.100000,0.000000
3,2019,5,6,4,0,18.1,1,0.000000,2.1,2019-05-06 04:00:00,...,0.000000,0.000000,1.947239,0.000000,0.000000,0.000000,291.25,291.250000,18.100000,0.000000
4,2019,5,6,5,0,18.1,1,0.000000,1.9,2019-05-06 05:00:00,...,0.000000,0.000000,4.726325,0.000000,0.000000,0.000000,291.25,291.250000,18.100000,0.000000
5,2019,5,6,6,0,18.1,1,5.555556,1.2,2019-05-06 06:00:00,...,0.000019,0.005556,0.011080,0.000003,0.059016,0.005186,291.25,291.372052,18.222052,0.820853
6,2019,5,6,7,0,18.4,1,66.666667,1.5,2019-05-06 07:00:00,...,0.000966,0.066667,0.689397,0.000400,0.120404,0.062303,291.55,293.016193,19.866193,9.819692
7,2019,5,6,8,0,20.1,1,263.888889,0.9,2019-05-06 08:00:00,...,0.042001,0.263889,0.865907,0.027562,0.398951,0.246102,293.25,299.041599,25.891599,38.193588
8,2019,5,6,9,0,20.4,1,119.444444,1.9,2019-05-06 09:00:00,...,0.001503,0.119444,0.942050,0.001284,0.112188,0.112052,293.55,296.186966,23.036966,17.518251
9,2019,5,6,10,0,20.0,1,72.222222,0.9,2019-05-06 10:00:00,...,0.000472,0.072222,0.980297,0.000469,0.080864,0.067715,293.15,294.743550,21.593550,10.625711

In [21]:
rf = Realtime.set_index('Time')
rf.columns

Index(['Year', 'Month', 'Day', 'Hour', 'Minute', 'Real_Temperature(2m)[°C]',
       'Real_Mean Sea Level Pressure[hpa]', 'Real_Radiation[W/m2]',
       'Real_Wind Speed(10m)[m/s]', 'ts', 'ω', 'n', 'δ the solar declination',
       'cosθ', 'θ(radian)', 'θ(degree)', 'cosθz', 'θz(radian)', 'θz(degree)',
       'Gon(the extraterrestrial normal radiation)[kW/m2]',
       'Go(the extraterrestrial horizontal radiation)[kW/m2]',
       '_Go(the extraterrestrial horizontal radiation averaged over the time step )[kW/m2]',
       'the global horizontal radiation[kW/m2]', 'kt(the clearness index)',
       '_Gd(the diffuse radiation)[kW/m2]', '_Gb(the beam radiation)[kW/m2]',
       '_G', 'Rb', 'Af', 'f', '_Gt', 'temperature[K]',
       'Tc(the PV cell temperature)[K]',
       'Real_Tc(the PV cell temperature)[°C]',
       'Real_Ppv(the output of the PV array)[Wh]'],
      dtype='object')

In [22]:
print(file_dir_path)

Realtime_CSV/

In [23]:
#データの書き出し
filename = file_dir_path+'/realtime'+year+month+day+time+'.csv'
Realtime.to_csv(filename,encoding="UTF-8")

# Wind calc

In [ ]:
V_COE = np.log(Realtime['Wind Speed(80m)[m/s]']/Realtime['Wind Speed(10m)[m/s]'])\
    /np.log(H_top/H_ref)


Realtime['V_COE[power law]']=V_COE
Realtime['ρ(air dencity)']=Realtime['Mean Sea Level Pressure[hpa]'] / (2.87*273.15+2.87*Realtime['Temperature(2m)[°C]'])
Realtime['Wind Speed('+str(H)+')[m/s]']=Realtime['Wind Speed(10m)[m/s]'] *(H / H_ref)**V_COE

In [ ]:
wind30_values =Realtime['Wind Speed('+str(H)+')[m/s]']

Pwt=(np.where((V_rat<=wind30_values) & (wind30_values <= V_CO), Pr,\
              np.where((V_CIN<=wind30_values) & (wind30_values <= V_rat), \
                       Pr*(wind30_values-V_CIN)/(V_rat-V_CIN),0 )))
#Pwt_STP
Pwt_STP=(atm_pre0/Realtime['ρ(air dencity)'].values)*Pwt

Realtime['Pwt[kW]']= pd.Series(Pwt)
Realtime['Pwt_STP[kW]']= pd.Series(Pwt_STP)

#よく使う列だけ表示
dis = Realtime.columns.tolist()
dis = ['Time','Pwt', 'Temperature(2m)[°C]','Wind Speed('+str(H)+')[m/s]', 'Mean Sea Level Pressure[hpa]','ρ(air dencity)',\
       'Shortwave Radiation[W/m2]', 'Wind Speed(10m)[m/s]',\
       'Wind Speed(80m)[m/s]','V_COE[power law]','Pwt_STP']

# Visualize realtime

In [ ]:
df_real = Realtime.set_index('Time')
df_real.columns

In [ ]:
#データの書き出し
filename = file_dir_path+'/realtime'+year+month+day+time+'.csv'
Realtime.to_csv(filename,encoding="SHIFT-JIS")